/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'twer' at '6/26/14 3:52 PM' with Gradle 1.11
 *
 * @author twer, @date 6/26/14 3:52 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
